"use client";

import { useEffect, useId, useRef, useState } from "react";
import { useTheme } from "next-themes";

export function Mermaid({ chart }: { chart: string }) {
  const id = useId();
  const containerRef = useRef<HTMLDivElement>(null);
  const { resolvedTheme } = useTheme();
  const [svg, setSvg] = useState<string>("");

  useEffect(() => {
    const renderDiagram = async () => {
      const mermaid = (await import("mermaid")).default;

      mermaid.initialize({
        startOnLoad: false,
        securityLevel: "loose",
        fontFamily: "inherit",
        theme: resolvedTheme === "dark" ? "dark" : "default",
      });

      // Generate a unique ID for this render
      const elementId = `mermaid-${id.replace(/:/g, "-")}-${Date.now()}`;

      try {
        const { svg: renderedSvg } = await mermaid.render(elementId, chart);
        setSvg(renderedSvg);
      } catch {
        // If render fails, show the raw chart as fallback
        setSvg(`<pre>${chart}</pre>`);
      }
    };

    renderDiagram();
  }, [chart, resolvedTheme, id]);

  if (!svg) {
    return <div className="animate-pulse h-32 bg-muted rounded" />;
  }

  // Note: dangerouslySetInnerHTML is safe here because the SVG content
  // is generated by the Mermaid library from trusted MDX diagram definitions,
  // not from user input.
  return (
    <div
      ref={containerRef}
      className="my-6 overflow-x-auto"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
