"use client";

import { useEffect, useId, useRef, useState } from "react";
import { useTheme } from "next-themes";

declare global {
  interface Window {
    mermaid?: {
      initialize: (config: Record<string, unknown>) => void;
      render: (
        id: string,
        text: string
      ) => Promise<{ svg: string; bindFunctions?: (element: Element) => void }>;
    };
  }
}

const MERMAID_CDN_URL = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";

export function Mermaid({ chart }: { chart: string }) {
  const id = useId();
  const containerRef = useRef<HTMLDivElement>(null);
  const { resolvedTheme } = useTheme();
  const [svg, setSvg] = useState<string>("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const renderDiagram = async () => {
      try {
        // Dynamically import mermaid from CDN
        const mermaidModule = await import(/* webpackIgnore: true */ MERMAID_CDN_URL);
        const mermaid = mermaidModule.default;

        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "loose",
          fontFamily: "inherit",
          theme: resolvedTheme === "dark" ? "dark" : "default",
        });

        // Generate a unique ID for this render
        const elementId = `mermaid-${id.replace(/:/g, "-")}-${Date.now()}`;

        const { svg: renderedSvg } = await mermaid.render(elementId, chart);
        setSvg(renderedSvg);
      } catch (error) {
        console.error("Mermaid rendering failed:", error);
        // If render fails, show the raw chart as fallback
        setSvg(`<pre>${chart}</pre>`);
      } finally {
        setLoading(false);
      }
    };

    renderDiagram();
  }, [chart, resolvedTheme, id]);

  if (loading) {
    return <div className="animate-pulse h-32 bg-muted rounded" />;
  }

  // SECURITY NOTE: dangerouslySetInnerHTML is safe here because the SVG content
  // is generated by the Mermaid library from trusted MDX diagram definitions,
  // not from user input. The chart prop comes from static MDX content authored
  // by developers, not from external/user sources.
  return (
    <div
      ref={containerRef}
      className="my-6 overflow-x-auto"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
