"use client";

import { useEffect, useId, useState } from "react";

const MERMAID_CDN_URL = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";

interface ThemeConfig {
  theme: "default" | "dark" | "forest" | "neutral" | "base";
  look?: "classic" | "handDrawn";
  themeVariables?: Record<string, string>;
}

interface MermaidDemoProps {
  chart: string;
  themeConfig: ThemeConfig;
  label: string;
  description?: string;
}

export function MermaidDemo({ chart, themeConfig, label, description }: MermaidDemoProps) {
  const id = useId();
  const [svg, setSvg] = useState<string>("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const renderDiagram = async () => {
      setLoading(true);
      try {
        const mermaidModule = await import(/* webpackIgnore: true */ MERMAID_CDN_URL);
        const mermaid = mermaidModule.default;

        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "loose",
          fontFamily: "inherit",
          theme: themeConfig.theme,
          look: themeConfig.look ?? "classic",
          ...(themeConfig.themeVariables && { themeVariables: themeConfig.themeVariables }),
        });

        const elementId = `mermaid-demo-${id.replace(/:/g, "-")}-${Date.now()}`;
        const { svg: renderedSvg } = await mermaid.render(elementId, chart);
        setSvg(renderedSvg);
      } catch (error) {
        console.error("Mermaid rendering failed:", error);
        setSvg(`<pre class="text-red-500">${error instanceof Error ? error.message : "Render failed"}</pre>`);
      } finally {
        setLoading(false);
      }
    };

    renderDiagram();
  }, [chart, themeConfig, id]);

  // SECURITY NOTE: dangerouslySetInnerHTML is safe here because the SVG content
  // is generated by the Mermaid library from hardcoded chart definitions in this
  // demo page, not from user input or external sources.
  return (
    <div className="rounded-lg border bg-card p-4">
      <div className="mb-3 border-b pb-2">
        <h3 className="font-semibold text-lg">{label}</h3>
        {description && <p className="text-sm text-muted-foreground">{description}</p>}
        <code className="mt-1 block text-xs text-muted-foreground bg-muted px-2 py-1 rounded">
          theme: "{themeConfig.theme}"{themeConfig.look === "handDrawn" && ', look: "handDrawn"'}
          {themeConfig.themeVariables && " + themeVariables"}
        </code>
      </div>

      {loading ? (
        <div className="animate-pulse h-48 bg-muted rounded" />
      ) : (
        <div
          className="overflow-x-auto [&>svg]:max-w-full [&>svg]:h-auto"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      )}
    </div>
  );
}
